#+TITLE: Luca's nix configuration
#+SLUG: nix
#+DATE: <2019-10-26>
#+AUTHOR: Luca Cambiaghi
#+STARTUP: show2levels
#+OPTIONS: toc:nil num:nil ^:nil

* Introduction
** This repository
This repository contains my system configuration.
The main objective is to have a portable and reproducible system in order to for example bootstrap a new system in a quick and automated way.
The ideal is to share packages and configuration across different operating systems.
At the moment I only use a ~macOS~ system but I am prepared for the day I will switch to ~nixOS~

Tools:
- ~nix~ as a package manager
  + In particular, an experimental feature called ~flake~ to achieve complete reproducibility
- ~home-manager~ to configure packages and dotfiles
- ~nix-darwin~ to configure macOS systems (e.g. it has a great ~brew~ module)

** This file
This file (~readme.org~) is used to generate (the correct term is ~tangle~) my ~flake.nix~ file, where I specify the inputs and outputs of my system configuration.
The tangled ~flake.nix~ file imports other ~.nix~ files (e.g. ~darwin/default.nix~).

This file is better viewed in HTML format [[https://luca.cambiaghi.me/nixpkgs/readme.html][here]] or through ~org-mode~ (clone the repo and open in ~emacs~).
You can visit my blog at the same [[https://luca.cambiaghi.me][website]].

* Practical commands
** First install

Use Determinate System installer.

** darwin-rebuild and updating of flakes

See =Makefile=

* brew86, pyenv86
Reference: https://sixty-north.com/blog/pyenv-apple-silicon.html
#+begin_src shell
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
alias brew86="arch -x86_64 /usr/local/bin/brew"

# brew86 install openssl readline sqlite3 xz zlib python@3.9
brew86 install python@3.11
#+end_src

