name: "Export"

on: [push]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Export Org files to GitHub Pages
      uses: tecosaur/org-knit-action@v0.2
      with:
        github_token: ${{ secrets.ORG_KNIT_PAT }}
        branch: gh-pages
        config: https://github.com/lccambiaghi/vanilla-emacs